apiVersion: apps/v1
kind: Deployment
metadata:
  name: down-deployment
  labels:
    app: down
spec:
  replicas: 1
  selector:
    matchLabels:
      app: down
  template:
    metadata:
      labels:
        app: down
    spec:
      volumes:
        - name: holy-storage
          persistentVolumeClaim:
            claimName: holy-pvc
      containers:
        - name: down
          volumeMounts:
            - name: holy-storage
              mountPath: /data
          image: down
          imagePullPolicy: Never
          env:
            - name: img_dir
              value: "/data/uploads"
            - name: song_dir
              value: "/data/downs"
            - name: public_url
              value: "http://localhost:30333"
